---
- ros_topic_name: /uav_0/cmd_vel
  gz_topic_name: /model/uav_0/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ

- ros_topic_name: /uav_0/pose_gt
  gz_topic_name: /model/uav_0/pose
  ros_type_name: geometry_msgs/msg/PoseStamped
  gz_type_name: gz.msgs.Pose
  direction: GZ_TO_ROS

- ros_topic_name: /uav_0/imu
  gz_topic_name: /model/uav_0/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS

- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS